#ifndef AUXFUNCTION_H
#define AUXFUNCTION_H

#include <cfloat>
#include <cmath>
#include <limits>

#include "hyperionlibrary_export.h"  // Automatically generated by CMake

namespace hypl
{
    namespace auxfunction
    {
        HYPERIONLIBRARY_EXPORT  double SolarDeclinationByDayNumber(int day_number);
        HYPERIONLIBRARY_EXPORT  double DistanceSunEarth(int day_number);
        HYPERIONLIBRARY_EXPORT  double ReceiverSubtendedAngle(double ratio_of_distances );

        template<class T>
        constexpr bool equals(T x, T y)
        {
            return std::abs(x - y) < std::numeric_limits<T>::epsilon();
        }
    }
}
#endif // AUXFUNCTION_H
